spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 325363078952-9snig7h2mddv8up2dlpmsbmal98t0l8v.apps.googleusercontent.com
            clientSecret: boHyTbOK5s5aYS11OW1fQCgM
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          github:
            clientId:
            clientSecret:
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8766/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect